import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_LANGUAGE } from '../../i18n/constants';

const ROOT_DIR = fileURLToPath(new URL('../../', import.meta.url));
const MODULES_DIR = join(ROOT_DIR, 'i18n', 'locales', DEFAULT_LANGUAGE);
const OUTPUT_FILE = join(ROOT_DIR, 'app', 'composables', 'useModuleI18n', 'types.ts');

export const generateI18nModuleTypes = () => {
  const moduleNames = readdirSync(MODULES_DIR, { withFileTypes: true })
    .filter(entry => entry.isFile() && entry.name.endsWith('.json'))
    .map(entry => entry.name.slice(0, -'.json'.length));

  const union = moduleNames.length ? moduleNames.map(name => `'${name}'`).join(' | ') : 'never';

  const content = [
    '// AUTO-GENERATED by config/generateI18nModuleTypes.ts (prepare:types hook). Do not edit.',
    `// Source: i18n/locales/${DEFAULT_LANGUAGE}/*.json — add a file there and restart dev (or run \`npx nuxt prepare\`).`,
    `export type I18nModuleType = ${union};`,
    '',
  ].join('\n');

  const current = existsSync(OUTPUT_FILE)
    ? readFileSync(OUTPUT_FILE, 'utf8').replace(/\r\n/g, '\n')
    : null;
  if (current === content) return;

  writeFileSync(OUTPUT_FILE, content);
};
