export type TColors = 'surface'
  | 'surface-container'
  | 'surface-high-container'
  | 'surface-low-container'
  | 'surface-highest-container'
  | 'surface-accent-container'
  | 'on-surface'
  | 'on-surface-secondary'
  | 'on-surface-tertiary'
  | 'outline'
  | 'outline-variant'

  | 'primary'
  | 'primary-variant'
  | 'secondary'
  | 'tertiary'
  | 'quality-fn'
  | 'quality-mv'
  | 'quality-ft'
  | 'quality-ww'
  | 'phase'
  | 'ruby'
  | 'pearl'
  | 'sapphire'
  | 'emerald'
  | 'attention'
  | 'error'
  | 'best-price'
  | 'good-price'
  | 'souvenir'
  | 'stattrak';

export type TSizes = 'xl' | 'l' | 'm' | 's';
